# Generated by Django 3.2 on 2022-08-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_auto_20220818_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmoneycollection',
            name='note',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='moneycollection',
            name='note',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
