# Generated by Django 3.2 on 2022-08-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0004_auto_20220818_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmoneycollection',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='moneycollection',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
