# Generated by Django 3.2 on 2022-08-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0005_auto_20220818_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='note',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historicalexpense',
            name='note',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
