# Generated by Django 3.2 on 2022-08-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0006_auto_20220818_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='attachment',
            field=models.FileField(blank=True, max_length=255, upload_to='expenses/% Y/% M/% D/', verbose_name='Attachment Path'),
        ),
        migrations.AddField(
            model_name='historicalexpense',
            name='attachment',
            field=models.TextField(blank=True, max_length=255, verbose_name='Attachment Path'),
        ),
        migrations.AddField(
            model_name='historicalmoneycollection',
            name='attachment',
            field=models.TextField(blank=True, max_length=255, verbose_name='Attachment'),
        ),
        migrations.AddField(
            model_name='moneycollection',
            name='attachment',
            field=models.FileField(blank=True, max_length=255, upload_to='collection/% Y/% M/% D/', verbose_name='Attachment'),
        ),
    ]
