# Generated by Django 3.2 on 2022-08-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0009_auto_20220818_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneycollection',
            name='attachment',
            field=models.ImageField(blank=True, max_length=255, upload_to='collection/%Y/%m/%d/', verbose_name='Attachment'),
        ),
    ]
