# Generated by Django 3.2 on 2022-08-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0011_auto_20220819_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmoneycollection',
            name='type',
            field=models.CharField(choices=[('VARGANI', 'Vargani'), ('SAVING', 'Saving'), ('OTHERS', 'Others')], default='VARGANI', max_length=300),
        ),
        migrations.AddField(
            model_name='moneycollection',
            name='type',
            field=models.CharField(choices=[('VARGANI', 'Vargani'), ('SAVING', 'Saving'), ('OTHERS', 'Others')], default='VARGANI', max_length=300),
        ),
    ]
