# Generated by Django 3.2 on 2022-08-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0012_auto_20220822_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmoneycollection',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI')], default='CASH', max_length=300, verbose_name='Payment Method'),
        ),
        migrations.AddField(
            model_name='moneycollection',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI')], default='CASH', max_length=300, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='historicalmoneycollection',
            name='type',
            field=models.CharField(choices=[('VARGANI', 'Vargani'), ('SAVING', 'Saving'), ('OTHERS', 'Others')], default='VARGANI', max_length=300, verbose_name='Collection Type'),
        ),
        migrations.AlterField(
            model_name='moneycollection',
            name='type',
            field=models.CharField(choices=[('VARGANI', 'Vargani'), ('SAVING', 'Saving'), ('OTHERS', 'Others')], default='VARGANI', max_length=300, verbose_name='Collection Type'),
        ),
    ]
