# Generated by Django 3.2 on 2022-08-22 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0013_auto_20220822_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmoneycollection',
            name='collection_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Collection Date'),
        ),
        migrations.AddField(
            model_name='moneycollection',
            name='collection_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Collection Date'),
        ),
    ]
