# Generated by Django 3.2 on 2022-08-22 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0014_auto_20220822_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expense_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Expense Date'),
        ),
        migrations.AddField(
            model_name='historicalexpense',
            name='expense_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Expense Date'),
        ),
    ]
