# Generated by Django 3.2 on 2022-08-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0015_auto_20220822_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmoneycollection',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('NOT_ACCEPTABLE', 'Not Acceptable')], default='PENDING', max_length=300),
        ),
        migrations.AlterField(
            model_name='moneycollection',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('NOT_ACCEPTABLE', 'Not Acceptable')], default='PENDING', max_length=300),
        ),
    ]
