# Generated by Django 3.2 on 2022-09-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0016_auto_20220823_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmoneycollection',
            name='type',
            field=models.CharField(choices=[('VARGANI', 'Ganpati Vargani'), ('MAHA_PRASAD_VARGANI', 'Mahaprasad Vargani'), ('SAVING', 'Saving'), ('OTHERS', 'Others')], default='VARGANI', max_length=300, verbose_name='Collection Type'),
        ),
        migrations.AlterField(
            model_name='moneycollection',
            name='type',
            field=models.CharField(choices=[('VARGANI', 'Ganpati Vargani'), ('MAHA_PRASAD_VARGANI', 'Mahaprasad Vargani'), ('SAVING', 'Saving'), ('OTHERS', 'Others')], default='VARGANI', max_length=300, verbose_name='Collection Type'),
        ),
    ]
