# Generated by Django 3.2 on 2023-09-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0017_auto_20220907_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='year',
            field=models.CharField(choices=[('2022', '2022'), ('2023', '2023'), ('2024', '2024')], default='2022', max_length=300),
        ),
        migrations.AddField(
            model_name='historicalexpense',
            name='year',
            field=models.CharField(choices=[('2022', '2022'), ('2023', '2023'), ('2024', '2024')], default='2022', max_length=300),
        ),
        migrations.AddField(
            model_name='historicalmoneycollection',
            name='year',
            field=models.CharField(choices=[('2022', '2022'), ('2023', '2023'), ('2024', '2024')], default='2022', max_length=300),
        ),
        migrations.AddField(
            model_name='moneycollection',
            name='year',
            field=models.CharField(choices=[('2022', '2022'), ('2023', '2023'), ('2024', '2024')], default='2022', max_length=300),
        ),
    ]
