# Generated by Django 3.2 on 2023-09-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0018_auto_20230913_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(blank=True, choices=[('GANESH_MURTHI', 'Ganesh Muthri'), ('POOJA_DECORATION', 'Pooja & Decoration'), ('GIFTS', 'Gifts'), ('MAHAPRASAD', 'Maha-Prasad'), ('ELECTRIC', 'Electric Kharch'), ('AHAVAL', 'Ahaval'), ('OTHERS', 'Others'), ('MIRAVNUK', 'Miravnuk'), ('MAGIL_BAKI', 'Magil Baki')], max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='historicalexpense',
            name='expense_type',
            field=models.CharField(blank=True, choices=[('GANESH_MURTHI', 'Ganesh Muthri'), ('POOJA_DECORATION', 'Pooja & Decoration'), ('GIFTS', 'Gifts'), ('MAHAPRASAD', 'Maha-Prasad'), ('ELECTRIC', 'Electric Kharch'), ('AHAVAL', 'Ahaval'), ('OTHERS', 'Others'), ('MIRAVNUK', 'Miravnuk'), ('MAGIL_BAKI', 'Magil Baki')], max_length=300, null=True),
        ),
    ]
